version: '3.7'

services:
  web-client:
    container_name: adempiere-ui-client
    network_mode: bridge
    build: .
    volumes:
      - /usr/app/
      - /usr/app/node_modules
    labels:
      - app=adempiere-vue
      - maintainer=EdwinBetanc0urt@outlook.com
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_PROXY_ADDRESS=20.12.0.105
      - VUE_APP_PROXY_PORT=8989
    # TODO: Add enviroment variables to ports
    ports:
      - 9526:9526 # Prod
      - 9527:9527 # Dev
