version: '3.7'

services:
  web-client:
    container_name: adempiere-ui-client
    network_mode: bridge
    build: .
    volumes:
      - /opt/Apps/adempiere-vue
      - /opt/Apps/adempiere-vue/node_modules
    labels:
      - app=adempiere-vue
      - maintainer=EdwinBetanc0urt@outlook.com
    stdin_open: true
    tty: true
    environment:
      - RELEASE_VERSION=3.9.3
      - VUE_APP_PROXY_ADDRESS=localhost
      - VUE_APP_PROXY_PORT=8989
    # TODO: Add enviroment variables to ports
    ports:
      - 9526:9526 # Prod
